
GET http://localhost:8000/products/ HTTP/1.1

### GET Product Details by id

GET http://localhost:8000/products/2 HTTP/1.1

###? PUT a Product
PUT http://localhost:8000/products/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3Mzg5OTI0LCJpYXQiOjE3MzczODk2MjQsImp0aSI6IjRhZTc3NjUwZTYzZDQwNTU5ZmIzNGI5ZDM0NWE1Y2FkIiwidXNlcl9pZCI6Mn0.DeSzzqyRgTNE_vrPxuxo3Hwzx9OI0nkRDUDfgTCiMIM

{
	"name": "Television",
	"price": 300.00,
	"stock": 14,
	"description": "An amazing new TV"
}

###! Delete a Product
DELETE  http://localhost:8000/products/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3MzY5OTAzLCJpYXQiOjE3MzczNjk2MDMsImp0aSI6IjQyMjdjYWYzODEwMTQ1N2I4OTU0M2JmMTk5NzFjODg1IiwidXNlcl9pZCI6Mn0.-VTssrbAJhaj20VsRgbejWd9McXbYQmG2kCKPMBa5Co


###? GET AccessToken
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
	"username": "admin",
	"password": "test"
}


###? User's Order by Auth credentials
GET http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NjE4OTA1LCJpYXQiOjE3Mzc2MTg2MDUsImp0aSI6Ijc1YjU1MDI1ODAxNDRlODU4Mjc0MDc2ZjczZWI1YWQ4IiwidXNlcl9pZCI6MX0.3-dGWkjxTymUI8lu1iF2dhgkPK13fLIrRpyyDsGi8y4


###? ALL User's Order
GET http://localhost:8000/orders/ HTTP/1.1

###? GET Refresh Token
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
	"refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNzQ1NDgwMywiaWF0IjoxNzM3MzY4NDAzLCJqdGkiOiIzZjRkOWNkYTM0MGU0MDE0OTE5MWE2MmJhNTZlM2ZkMyIsInVzZXJfaWQiOjJ9.T6EFcm1DeaBHGTx0TnI3dxU1NrvkxzAcKsHPEWm4uh0"

}



###? POST WITH AccessToken

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3Mzg5OTI0LCJpYXQiOjE3MzczODk2MjQsImp0aSI6IjRhZTc3NjUwZTYzZDQwNTU5ZmIzNGI5ZDM0NWE1Y2FkIiwidXNlcl9pZCI6Mn0.DeSzzqyRgTNE_vrPxuxo3Hwzx9OI0nkRDUDfgTCiMIM

{
	"name": "Test",
	"price": 300.00,
	"stock": 14,
	"description": "An amazing new TV"
}


###? POST Order
POST http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzIyNTU4LCJpYXQiOjE3Mzc3MjIyNTgsImp0aSI6ImFjODYwYjExZWY4ZjQwYjJhZDdhZGM3NmZhN2M5ZjBiIiwidXNlcl9pZCI6MX0.MJkLuN0PdWwydhc_3LLN2oe1209Oh6fxfPfCCUKgIRw

{
	"status": "Pending",
	"items": [
		{
				"product": 10,
				"quantity": 20
		},
		{
				"product": 3,
				"quantity": 1
		}
	]
}
###? User's Order by Auth credentials
GET http://localhost:8000/orders/47c344a4-2743-4b21-9ae7-488cf34c28aa HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzMzNTc5LCJpYXQiOjE3Mzc3MzMyNzksImp0aSI6IjNjNTQ3ZDYwMWMwODQ2NjdhMWEzOTRmZjEwN2FjYmM5IiwidXNlcl9pZCI6MX0.zzYASfarm5aUsnmYk8wkdxjJkEsuGnUQlDPbJegP7To
###? Update a Order
PUT  http://localhost:8000/orders/47c344a4-2743-4b21-9ae7-488cf34c28aa/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzMzNTc5LCJpYXQiOjE3Mzc3MzMyNzksImp0aSI6IjNjNTQ3ZDYwMWMwODQ2NjdhMWEzOTRmZjEwN2FjYmM5IiwidXNlcl9pZCI6MX0.zzYASfarm5aUsnmYk8wkdxjJkEsuGnUQlDPbJegP7To

{
	"status": "Pending"
}
###! Delete a Order

DELETE   http://localhost:8000/orders/47c344a4-2743-4b21-9ae7-488cf34c28aa/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzMzNTc5LCJpYXQiOjE3Mzc3MzMyNzksImp0aSI6IjNjNTQ3ZDYwMWMwODQ2NjdhMWEzOTRmZjEwN2FjYmM5IiwidXNlcl9pZCI6MX0.zzYASfarm5aUsnmYk8wkdxjJkEsuGnUQlDPbJegP7To



###? GET AccessToken
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
	"username": "saikat",
	"password": "sa"
}